version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Host:Container
    environment:
      # These will override .env file if both are present and Dockerfile doesn't hardcode them
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/todoapidb # Connects to the mongo service below
      - JWT_SECRET=yourjwtsecretkeypleasechangeMatthewCompose # Use a different one for compose
      - NODE_ENV=development # Set to development for local compose
    depends_on:
      - mongo
    volumes: # For development: mounts local code into container for hot-reloading if nodemon is CMD
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevents local node_modules from overwriting container's
    # command: npm run dev # If you want nodemon to run inside the container for hot reload

  mongo:
    image: mongo:latest # Or a specific version like mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persists MongoDB data
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local # Explicitly define driver